spring:
  application:
    name: Property Management System
  datasource:
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 6f8d6b84a07054
    password: 12f15b319102c2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  email:
    sender: notifications@nexthome.com
server:
  port: ${API_LISTENING_PORT:8080}