spring:
  application:
    name: Property Management System
  datasource:
    username: pms
    password: pms
    url: jdbc:postgresql://localhost:5432/pms
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  email:
    sender: sender@example.com
server:
  port: 8080